"""
Module containing helper functions for post processing as required in 
other parts of the valpas package
"""

import numpy as np
import pandas as pd

def sort_associations(df: pd.DataFrame) -> pd.Series:
    """
    Takes a matrix like pandas Dataframe object, extracts the upper 
    triangle, stacks and sorts the cell values.
    
    Returns a sorted pandas Series object with a multiindex comprised 
    of index pairs from *df* as axis labels and the value of the *df* 
    cell as values.
    """
    upper_tri = np.triu(df, -1)
    upper_tri[np.tril_indices(upper_tri.shape[0], 0)] = np.nan

    df_upper_tri = pd.DataFrame(
        data=upper_tri,
        index=df.index,
        columns=df.columns
        )

    df_sorted = df_upper_tri.stack().sort_values(ascending=False)

    return df_sorted

def beautify_series(df: pd.Series) -> pd.DataFrame:
    """
    Takes a `pd.Series` object (for example generated by 
    `sort_associations()`), extracts the index names and transforms the 
    Series into a `pd.DataFrame` with column 1 & 2 being the indices 
    of the Series and column 3 the value.
    """
    if df.index.names[0] == df.index.names[1]:
        id_1 = '_'.join([df.index.names[0], '1'])
        id_2 = '_'.join([df.index.names[0], '2'])
    else:
        id_1 = df.index.names[0]
        id_2 = df.index.names[1]
    df_return = pd.DataFrame({
        id_1: df.index.get_level_values(0),
        id_2: df.index.get_level_values(1),
        'Correlation': df.values
        })
    return df_return