[build-system]
requires = [
  "hatchling",
  "hatch-vcs",
  ]
build-backend = "hatchling.build"

[project]
name = "valpas"
description = ''

requires-python = ">=3.12"
authors = [
  { name = "Yannick Mahlich", email = "yannick.mahlich@pnnl.gov" },
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
  "bspline-mutual-information",
  "matplotlib",
  "networkx",
  "numpy",
  "pandas",
  "plotly",
  "openpyxl",
  "scikit-learn",
  "scipy",
  "seaborn",
  "torch"
]
dynamic = [
  "version",
  ]
readme = "README.md"
license = {text = "2-clause BSD"}

[project.scripts]
valpas = "valpas.cli:main"

[project.urls]
Documentation = "https://github.com/PNNL-Predictive-Phenomics/valpas#readme"
Issues = "https://github.com/PNNL-Predictive-Phenomics/valpas/issues"
Source = "https://github.com/PNNL-Predictive-Phenomics/valpas"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/valpas/_version.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
]
