"""
Module containing functions for the visualization of association data 
generated by VaLPAS via heatmaps.
"""


import numpy as np
import pandas as pd

import matplotlib
from matplotlib.axes import Axes
import matplotlib.pyplot as plt


def heatmap(
        data: np.ndarray,
        col_labels: list,
        row_labels: list,
        ax: Axes=None,
        cbar_kw: dict=None,
        cbarlabel: str='',
        **kwargs):
    """
    _summary_

    Parameters
    ----------
    data : np.ndarray
        Matrix with association values.
    col_labels : list
        List of column labels for the plot.
    row_labels : list
        List of row labels for the plot.
    ax : Axes, default=None
        matplotlib Axes element that should be modified. If omitted the 
        function attempts to extract the Axes element from the most
        recent plot.
    cbar_kw : dict, default=None
        keyword arguments that are passed along to the color bar.
    cbarlabel : str, default=''
        Name for the colorbar.
    kwargs : Any
        Additional keyword arguments that will be passed to matplotlib

    Returns
    -------
    tuple
        Returns an image, and colorbar object.
    """
    
    if ax is None:
        ax = plt.gca()

    if cbar_kw is None:
        cbar_kw = {}
    
    im = ax.imshow(data, **kwargs)

    cbar = ax.figure.colorbar(im, ax=ax, **cbar_kw)
    cbar.ax.set_ylabel(cbarlabel, rotation=-90, va="bottom")

    ax.set_xticks(np.arange(len(col_labels)), labels=col_labels)
    ax.set_yticks(np.arange(len(row_labels)), labels=row_labels)

    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
            rotation_mode="anchor")

    ax.spines[:].set_visible(False)

    ax.set_xticks(np.arange(data.shape[1]+1)-.5, minor=True)
    ax.set_yticks(np.arange(data.shape[0]+1)-.5, minor=True)
    ax.grid(which="minor", color="w", linestyle='-', linewidth=3)
    ax.tick_params(which="minor", bottom=False, left=False)

    return im, cbar

def annotate_heatmap(im, data=None, valfmt="{x:.2f}",
                     textcolors=("black", "white"),
                     threshold=None, **textkw):
    """
    A function to annotate a heatmap.

    Parameters
    ----------
    im
        The AxesImage to be labeled.
    data
        Data used to annotate.  If None, the image's data is used.  Optional.
    valfmt
        The format of the annotations inside the heatmap.  This should either
        use the string format method, e.g. "$ {x:.2f}", or be a
        `matplotlib.ticker.Formatter`.  Optional.
    textcolors
        A pair of colors.  The first is used for values below a threshold,
        the second for those above.  Optional.
    threshold
        Value in data units according to which the colors from textcolors are
        applied.  If None (the default) uses the middle of the colormap as
        separation.  Optional.
    **kwargs
        All other arguments are forwarded to each call to `text` used to create
        the text labels.
    """

    if not isinstance(data, (list, np.ndarray)):
        data = im.get_array()

    # Normalize the threshold to the images color range.
    if threshold is not None:
        threshold = im.norm(threshold)
    else:
        threshold = im.norm(data.max())/2.

    # Set default alignment to center, but allow it to be
    # overwritten by textkw.
    kw = dict(horizontalalignment="center",
              verticalalignment="center")
    kw.update(textkw)

    # Get the formatter in case a string is supplied
    if isinstance(valfmt, str):
        valfmt = matplotlib.ticker.StrMethodFormatter(valfmt)

    # Loop over the data and create a `Text` for each "pixel".
    # Change the text's color depending on the data.
    texts = []
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            kw.update(color=textcolors[int(im.norm(data[i, j]) > threshold)])
            text = im.axes.text(j, i, valfmt(data[i, j], None), **kw)
            texts.append(text)

    return texts


def create_fig(df: pd.DataFrame, fig_out: str=None, cbarlabel: str=None):
    """
    Helper function to generate figure.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame that contains association values to be plotted.
    fig_out : str, default=None
        Path to where the figure should be saved. If fig_out is omitted,
        the Figure is not saved.
    cbarlabel : str, default=None
        Name for the colorbar.
    """
    df_np = df.to_numpy()
    col_labels = df.columns.values.tolist()
    row_labels = df.index.values.tolist()

    fig, ax = plt.subplots()

    im, cbar = heatmap(
        data=df_np,
        ax=ax,
        col_labels=col_labels, row_labels=row_labels,
        cbarlabel=cbarlabel, cmap='gist_heat'
        )
    texts = annotate_heatmap(im, textcolors=('white', 'black'), valfmt="{x:.1f}")

    fig.tight_layout()
    if fig_out is not None:
        plt.savefig(fig_out)
    else:
        plt.show()